executor: go
steps:
  - github-status/pending
  - checkout
  - restore_go_cache
  - attach_workspace:
      at: .
  - run:
      name: Build dev binary
      command: |
        set -eux -o pipefail

        # Move dev UI assets to expected location
        rm -rf ./pkg
        mkdir ./pkg

        # Build dev binary
        make bootstrap dev
  - persist_to_workspace:
      root: .
      paths:
        - bin
  - github-status/report
